---
Rakefile:
  unmanaged: true
.travis.yml:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 4.2.3
      RUBY_VER: 21-x64
  test_script:
    - 'bundle exec rspec spec/unit spec/integration -fd -b'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Josh Cooper, original author'
      begin: 2013
    - name: 'Puppet, Inc.'
      begin: 2013
      end: 'latest'
